version: "3"

services:
  floaty-backend:
    image: matthaeusheer/floaty-backend:0.0.6
    build: .
    ports:
      - "8080:8080"  # Expose the backend on localhost:8080 to access the application from the host
    environment:
      - SPRING_PROFILES_ACTIVE=docker-compose
    networks:
      - backend-network
    depends_on:
      - floaty-db-service
  floaty-db-service:
    image: mysql:8.0
    ports:
      - "3306:3306"  # Handy for debugging if the backend is started on the host and not in docker network
    networks:
      - backend-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=floaty-db
      - MYSQL_USER=db-user
      - MYSQL_PASSWORD=db-password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost --silent" ]
      interval: 3s
      timeout: 3s
      retries: 20
  smtp-server:
    image: rnwood/smtp4dev
    ports:
      - "5001:80"    # Expose the web UI on localhost:5001
      - "2525:25"    # Expose the SMTP server on localhost:2525, handy for debugging
    networks:
        - backend-network
networks:
  backend-network:
    driver: bridge
