version: "3"

services:
  floaty-backend:
    image: matthaeusheer/floaty-backend:0.0.9
    build: .
    ports:
      - "8080:8080"  # Expose the backend on localhost:8080 to access the application from the host
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - backend-network
    depends_on:
      floaty-db-service:
        condition: service_healthy
  floaty-db-service:
    image: mysql:8.0
    ports:
      - "3306:3306"  # Handy for debugging if the backend is started on the host and not in docker network
    networks:
      - backend-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot", "--execute", "SHOW DATABASES;"]
      interval: 3s
      retries: 30
      timeout: 5s
  smtp-server:
    image: rnwood/smtp4dev
    ports:
      - "5001:80"    # Expose the web UI on localhost:5001
      - "2525:25"    # Expose the SMTP server on localhost:2525, handy for debugging
    networks:
        - backend-network
networks:
  backend-network:
    driver: bridge
