version: "3"

services:
  floaty-db-service:
    image: mysql:8.0
    ports:
      - "3306:3306" # Expose MySQL on localhost:3306 (the classic mysql port)
    networks:
      - backend-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=floaty-db
      - MYSQL_USER=db-user
      - MYSQL_PASSWORD=db-password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  smtp-server:
    image: rnwood/smtp4dev
    ports:
      - "5001:80"    # Expose the web UI on localhost:5001
      - "2525:25"    # Expose the SMTP server on localhost:2525
  floaty-backend:
    image: matthaeusheer/floaty-backend:latest
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend-network
    depends_on:
      - floaty-db-service
networks:
  backend-network:
    driver: bridge
