---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-env
  namespace: floaty
spec:
  encryptedData:
    RENOVATE_TOKEN: AgAGLaJ2TAxfHyus11V0FeFUTe5vWVGqJyJGfTcz+hTULES/yHn6AtIei0apNKMB+LarNAl+EZ7eEw8Jdlds3Gt+mj0q9ZqUFntTnsCwZfX9AbDfPvZbGVPhrafv41P4kfVM7t3w18dcVU2cpppO+mmnryLS5dDGRjgffDLhI8UDXBfEAB2GOX2pXrqqEt2lDX8g8fNcqtkZi2mizPDJZZkbhw1gz4Dks79frMrKs5cOern91H1w3UPIiPMgh5AfRVi6Qa/UHwupzFzN06ENVRYIJVLIqLlvNVtYStxfZPeDBlpGutkT86OqAF7YqJXXMuXsOjfDdWaG9RJU/qYSQ68qwZoRrbtNfJmbcQCJOFVXadI+P9TNelR41QhPt7HeO2FwbYxggukektla8vI7G1SbZdwwPwcxUXt04uzuEZvFos8u/ZxiTgcGhEw7Eac+RyG+NRIi6+WR9Z8Z0e5tKUCzY3X1Y8AnEEBZCcW5fR8jlmaaJT/na5jxBWlZJa0g62L+emMfsl8TAAdpyHlnfl7z8PFGXm+6FodGRiL1gqZ+01/WcjE0GDdKRESQErgsxykE0bKwcV9OvHvb4YKCg+ns86wXzHp1/3z+z1TaWditIpC0L1GuUB9WjW7225Qh0rXgPdujTfAPxUBm45NUS0RTYFTuYr4kpI9uq4+X9dzNLfnQjHhLI6HHVR2QOtcMv7QnrTHtTg+O/7oIYxkix6gvxEQzDQVB2gLkRxBff66bEBIEmsRTQruJ
  template:
    metadata:
      name: renovate-env
      namespace: floaty
