apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-vms
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FloatyFly/floaty-backend
    targetRevision: main
    path: argocd/kubevirt
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
