apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://docs.renovatebot.com/helm-charts
      chart: renovate
      targetRevision: 38.x.x
      helm:
        valueFiles:
          - $values/argocd/renovate/values.yaml
    - repoURL: https://github.com/FloatyFly/floaty-backend
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: floaty
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
