openapi: 3.0.3
info:
  title: Floaty API
  description: |-
    The backend API for floaty. Just an example. Needs to be developped. \
    You might use [https://editor-next.swagger.io/]() for development.
  version: 0.0.1
tags:
  - name: users
    description: Look up all the users you want.

paths:
  /users:
    get:
      tags:
        - users
      summary: Find all users.
      description: Returns a list of users.
      operationId: getUsers
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{userId}:
    get:
      tags:
        - users
      summary: Find user by ID.
      description: Returns a single user.
      operationId: findUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


components:
  schemas:
    User:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          description: 'A unique id for this user. Property must not be given when creating a new user.'
          maxLength: 14
          example: 'USER0000123456'
          pattern: 'USER[0-9]{10}'
        name:
          type: string
          example: 'Free Willy'
          description: 'The name of the user.'
