name: AzureSpringApps
on:
  workflow_dispatch:  # Only triggers manually, not on push or PR
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: TODO

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: Deploy to Azure Spring App
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: maven build, clean
        run: |
          mvn clean package -Dspring.profiles.active=azure-dev

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: asa-floaty-backend
          app-name: app-floaty-backend
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/**/floaty-*.jar
