# .github/workflows/BuildAndPush.yml

name: Docker Build and Push Pipeline

on:
  push:
    branches:
      - master  # Trigger on merges to master
  release:
    types:
      - created  # Trigger on tag creation

env:
  IMAGE_NAME: matthaeusheer/floaty-backend

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ github.event_name == 'release' && 'refs/tags/' || '' }}${{ github.ref_name }}
