name: Docker Test Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests in Docker Container
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: false
          tags: test-image:latest
          build-args: |
            SKIP_TESTS=false

      - name: Run Tests
        run: |
          docker run --rm -v ${{ github.workspace }}/surefire-reports:/app/target/surefire-reports test-image:latest

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ./surefire-reports

