name: Docker Test Pipeline

on:
  pull_request:
    branches:
      - master  # Trigger when PRs are opened or synchronized to be merged into master
    types: [opened, synchronize, closed]  # Run on PR creation, updates, and closure
  push:
    branches:
      - master  # Trigger when something is directly pushed to master (e.g., from PR merge)

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests in Docker Container
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: false
          tags: test-image:latest
          build-args: |
            SKIP_TESTS=false
          outputs: |
            type=local,dest=/tmp/build-output
